# -*- coding: utf-8 -*-
"""Brain Tumor Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGvaGd7Ut9gqI2vE4wachni8ZQQnWSyO

# **Brain Tumor CNN**
**Dataset**
https://www.kaggle.com/datasets/tombackert/brain-tumor-mri-data?resource=download

**Models**
Xception, ResNet50, InceptionV3

## **Data Preprocessing**
"""

from google.colab import drive
drive.mount('/content/drive')

import os

data_path = '/content/drive/MyDrive/Thesis Data/brain-tumor-data/brain-tumor-mri-dataset'
print(os.listdir(data_path))

"""


- Relatively **balanced dataset**"""

data_path = '/content/drive/MyDrive/Thesis Data/brain-tumor-data/brain-tumor-mri-dataset'
classes = ['glioma', 'meningioma', 'notumor', 'pituitary']

for cls in classes:
    cls_path = os.path.join(data_path, cls)
    images = [f for f in os.listdir(cls_path) if f.lower().endswith(('.jpg'))]
    print(f"{cls.capitalize()}: {len(images)} images")

"""**EDA Class Count Bar Chart**
- Notumor, Pituitary, Meningioma, Glioma, respectively.
"""

import matplotlib.pyplot as plt

class_counts = {
   'Glioma': 1641,
    'Meningioma': 1775,
    'Notumor': 2000,
    'Pituitary': 1777
}

plt.figure(figsize=(10, 6))
plt.bar(class_counts.keys(), class_counts.values(), color=['#4682B4', '#696969', '#778899', '#A9A9A9'])  # Use shades of blue and gray
plt.xlabel('Tumor Type')
plt.ylabel('Number of Images')
plt.title('Number of Images per Brain Tumor Class')

plt.xticks(rotation=45, ha='right')

plt.show()

""" **Display Sample Images per Class**"""

import os
import random
from PIL import Image
import matplotlib.pyplot as plt

classes = ['glioma', 'meningioma', 'notumor', 'pituitary']
data_path = '/content/drive/MyDrive/Thesis Data/brain-tumor-data/brain-tumor-mri-dataset'

plt.figure(figsize=(12, 8))

for i, tumor_class in enumerate(classes):
    class_path = os.path.join(data_path, tumor_class)
    images = os.listdir(class_path)
    sample_imgs = random.sample(images, 3)

    for j, img_name in enumerate(sample_imgs):
        img_path = os.path.join(class_path, img_name)
        img = Image.open(img_path)

        plt.subplot(4, 3, i*3 + j + 1)
        plt.imshow(img, cmap='gray')
        plt.title(f'{tumor_class.capitalize()}')
        plt.axis('off')

plt.tight_layout()
plt.show()

"""**Check Image Size to Ensure Consistency**

"""

from PIL import Image
from collections import Counter

image_sizes = []

for tumor_class in classes:
    class_path = os.path.join(data_path, tumor_class)
    images = os.listdir(class_path)
    sample_imgs = random.sample(images, 100)  #

    for img_name in sample_imgs:
        try:
            img_path = os.path.join(class_path, img_name)
            img = Image.open(img_path)
            image_sizes.append(img.size)
        except:
            continue

print("Top 10 most common image sizes:")
print(Counter(image_sizes).most_common(10))

import numpy as np
import cv2
from tensorflow.keras.utils import to_categorical

img_size = 224
X = []
y = []

classes = ['glioma', 'meningioma', 'notumor', 'pituitary']
label_map = {'glioma': 0, 'meningioma': 1, 'notumor': 2, 'pituitary': 3}

for tumor_class in classes:
    class_path = os.path.join(data_path, tumor_class)
    for img_name in os.listdir(class_path):
        img_path = os.path.join(class_path, img_name)
        try:
            img = cv2.imread(img_path)
            img = cv2.resize(img, (img_size, img_size))
            X.append(img)
            y.append(label_map[tumor_class])
        except:
            continue

from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

X = np.array(X)
y = to_categorical(y, num_classes=4)

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42)

print("Training set:", X_train.shape, y_train.shape)
print("Validation set:", X_val.shape, y_val.shape)
print("Test set:", X_test.shape, y_test.shape)

"""**Data Augmentation**
- ONLY used for FINAL IncetpionV3
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rotation_range=10,
    width_shift_range=0.05,
    height_shift_range=0.05,
    zoom_range=0.1,
    horizontal_flip=True,
    brightness_range=(0.8, 1.2),
    fill_mode='nearest'
)
val_test_datagen = ImageDataGenerator()  # No augmentation for validation or test

train_generator = train_datagen.flow(X_train, y_train, batch_size=32)
val_generator = val_test_datagen.flow(X_val, y_val, batch_size=32)
test_generator = val_test_datagen.flow(X_test, y_test, batch_size=32, shuffle=False)

"""# **Model Development**

### **Model Development - Xception**
"""

from tensorflow.keras.applications import Xception
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout, Input
from tensorflow.keras.optimizers import Adamax

xception_base = Xception(weights='imagenet', include_top=False, input_tensor=Input(shape=(224, 224, 3)))

for layer in xception_base.layers:
    layer.trainable = False

x = xception_base.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.5)(x)
x = Dense(128, activation='relu')(x)
xception_output = Dense(4, activation='softmax')(x)

xception_model = Model(inputs=xception_base.input, outputs=xception_output)

xception_model.compile(optimizer=Adamax(learning_rate=0.001),
                       loss='categorical_crossentropy',
                       metrics=['accuracy'])


xception_model.summary()


from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

checkpoint = ModelCheckpoint('xception_initial.h5', monitor='val_loss', save_best_only=True, verbose=1)
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)

history = xception_model.fit(
    train_generator,
    epochs=20,
    validation_data=val_generator,
    callbacks=[checkpoint, early_stop]
)

xception_model.load_weights('xception_initial.h5')

"""### **Xception Fine-Tuning**"""

for layer in xception_base.layers:
    layer.trainable = True


xception_model.compile(optimizer=Adamax(learning_rate=1e-5),
                       loss='categorical_crossentropy',
                       metrics=['accuracy'])

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

xception_finetune_checkpoint = ModelCheckpoint('xception_finetuned.h5', monitor='val_loss', save_best_only=True, verbose=1)
xception_finetune_earlystop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)

xception_finetune_history = xception_model.fit(
    train_generator,
    epochs=20,
    validation_data=val_generator,
    callbacks=[xception_finetune_checkpoint, xception_finetune_earlystop]
)

"""### **Xception Test Set Results**"""

from tensorflow.keras.models import load_model

best_xception_model = load_model('xception_finetuned.h5')

test_loss, test_acc = best_xception_model.evaluate(test_generator, verbose=1)
print(f" Test Accuracy: {test_acc:.4f}")
print(f" Test Loss: {test_loss:.4f}")

"""**Xception GradCAM Testing**

"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import cv2

model = tf.keras.models.load_model('xception_finetuned.h5')

last_conv_layer_name = 'block14_sepconv2_act'

img_index = 10
img = X_test[img_index]
img_array = np.expand_dims(img, axis=0)

true_label = np.argmax(y_test[img_index])

grad_model = tf.keras.models.Model(
    [model.inputs],
    [model.get_layer(last_conv_layer_name).output, model.output]
)

with tf.GradientTape() as tape:
    conv_outputs, predictions = grad_model(img_array)
    predicted_class = tf.argmax(predictions[0])
    loss = predictions[:, predicted_class]


grads = tape.gradient(loss, conv_outputs)


pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))


conv_outputs = conv_outputs[0]
heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
heatmap = tf.squeeze(heatmap)
heatmap = np.maximum(heatmap, 0)
heatmap /= tf.math.reduce_max(heatmap)

img_original = (img * 255).astype("uint8")
heatmap = cv2.resize(heatmap.numpy(), (img_original.shape[1], img_original.shape[0]))
heatmap = np.uint8(255 * heatmap)
heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)

superimposed_img = cv2.addWeighted(img_original, 0.6, heatmap, 0.4, 0)

plt.figure(figsize=(12, 4))
plt.subplot(1, 3, 1)
plt.imshow(img_original)
plt.title(f"Original - True: {true_label}")
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(heatmap)
plt.title("Grad-CAM Heatmap")
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(superimposed_img)
plt.title(f"Predicted: {predicted_class.numpy()}")
plt.axis('off')

plt.tight_layout()
plt.show()

"""**Xception Accuracy and Loss Plots**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy (initial)')
plt.plot(history.history['val_accuracy'], label='Val Accuracy (initial)')
plt.plot(xception_finetune_history.history['accuracy'], label='Train Accuracy (fine-tune)')
plt.plot(xception_finetune_history.history['val_accuracy'], label='Val Accuracy (fine-tune)')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss (initial)')
plt.plot(history.history['val_loss'], label='Val Loss (initial)')
plt.plot(xception_finetune_history.history['loss'], label='Train Loss (fine-tune)')
plt.plot(xception_finetune_history.history['val_loss'], label='Val Loss (fine-tune)')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""## **Model Development - ResNet50**"""

from tensorflow.keras.applications import ResNet50

resnet_base = ResNet50(weights='imagenet', include_top=False, input_tensor=Input(shape=(224, 224, 3)))

for layer in resnet_base.layers:
    layer.trainable = False

x = resnet_base.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.5)(x)
x = Dense(128, activation='relu')(x)
resnet_output = Dense(4, activation='softmax')(x)

resnet_model = Model(inputs=resnet_base.input, outputs=resnet_output)

resnet_model.compile(optimizer=Adamax(learning_rate=0.001),
                     loss='categorical_crossentropy',
                     metrics=['accuracy'])

resnet_model.summary()


resnet_checkpoint = ModelCheckpoint('resnet_initial.h5', monitor='val_loss', save_best_only=True, verbose=1) #saves best model in resnet_initial.h5 file
resnet_early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)

resnet_history = resnet_model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_val, y_val),
    callbacks=[resnet_checkpoint, resnet_early_stop]
)

resnet_model.load_weights('resnet_initial.h5')

"""### **Fine-Tuning ResNet50**"""

for layer in resnet_base.layers:
    layer.trainable = True

resnet_model.compile(optimizer=Adamax(learning_rate=1e-5),
                     loss='categorical_crossentropy',
                     metrics=['accuracy'])

resnet_finetune_checkpoint = ModelCheckpoint('resnet_finetuned.h5', monitor='val_loss', save_best_only=True, verbose=1)
resnet_finetune_earlystop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)

resnet_finetune_history = resnet_model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_val, y_val),
    callbacks=[resnet_finetune_checkpoint, resnet_finetune_earlystop]
)

"""### **ResNet50 Test Set Results**"""

from tensorflow.keras.models import load_model

resnet_model = load_model('resnet_finetuned.h5')

resnet_test_loss, resnet_test_acc = resnet_model.evaluate(X_test, y_test, verbose=1)
print(f" ResNet Test Accuracy: {resnet_test_acc:.4f}")
print(f" ResNet Test Loss: {resnet_test_loss:.4f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(resnet_history.history['accuracy'], label='Train Accuracy (initial)')
plt.plot(resnet_history.history['val_accuracy'], label='Val Accuracy (initial)')
plt.plot(resnet_finetune_history.history['accuracy'], label='Train Accuracy (fine-tune)')
plt.plot(resnet_finetune_history.history['val_accuracy'], label='Val Accuracy (fine-tune)')
plt.title('Training and Validation Accuracy (ResNet)')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(resnet_history.history['loss'], label='Train Loss (initial)')
plt.plot(resnet_history.history['val_loss'], label='Val Loss (initial)')
plt.plot(resnet_finetune_history.history['loss'], label='Train Loss (fine-tune)')
plt.plot(resnet_finetune_history.history['val_loss'], label='Val Loss (fine-tune)')
plt.title('Training and Validation Loss (ResNet)')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""### **Model Development - InceptionV3**
**First Inception Version**
"""

from tensorflow.keras.applications import InceptionV3
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout, Input
from tensorflow.keras.optimizers import Adamax

inception_base = InceptionV3(weights='imagenet', include_top=False, input_tensor=Input(shape=(224, 224, 3)))

for layer in inception_base.layers:
    layer.trainable = False

x = inception_base.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.5)(x)
x = Dense(128, activation='relu')(x)
inception_output = Dense(4, activation='softmax')(x)

inception_model = Model(inputs=inception_base.input, outputs=inception_output)

inception_model.compile(optimizer=Adamax(learning_rate=0.001),
                        loss='categorical_crossentropy',
                        metrics=['accuracy'])

inception_model.summary()

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

checkpoint = ModelCheckpoint('inception_initial.h5', monitor='val_loss', save_best_only=True, verbose=1)
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)

history = inception_model.fit(
    train_generator,
    epochs=20,
    validation_data=val_generator,
    callbacks=[checkpoint, early_stop]
)

"""### **First Fine-Tuning: InceptionV3**"""

for layer in inception_base.layers:
    layer.trainable = True

inception_model.compile(optimizer=Adamax(learning_rate=1e-5),
                        loss='categorical_crossentropy',
                        metrics=['accuracy'])


from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

inception_finetune_checkpoint = ModelCheckpoint('inception_finetuned.h5', monitor='val_loss', save_best_only=True, verbose=1)
inception_finetune_earlystop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)

inception_finetune_history = inception_model.fit(
    train_generator,
    epochs=20,
    validation_data=val_generator,
    callbacks=[inception_finetune_checkpoint, inception_finetune_earlystop]
)

"""### **Initial Model Comparison**"""

import pandas as pd

model_names = ['Xception', 'ResNet50', 'InceptionV3']
test_accuracies = [0.9574, 0.9601, 0.9648]
test_losses = [0.1096, 0.1563, 0.0988]

results_df = pd.DataFrame({
    'Model': model_names,
    'Test Accuracy': test_accuracies,
    'Test Loss': test_losses
})

print("Model Comparison")
results_df

"""###**Retraining Inception with Data Augmentation and Learning Rate Scheduler**

### **Model Training - InceptionV3**
Data Augmentation and Learning Rate Scheduler Included
"""

from tensorflow.keras.applications import InceptionV3
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

inception_base = InceptionV3(weights='imagenet', include_top=False, input_tensor=Input(shape=(224, 224, 3)))

for layer in inception_base.layers:
    layer.trainable = False

x = inception_base.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.5)(x)
x = Dense(128, activation='relu')(x)
inception_output = Dense(4, activation='softmax')(x)

inception_model = Model(inputs=inception_base.input, outputs=inception_output)

inception_model.compile(optimizer=Adamax(learning_rate=5e-4),
                        loss='categorical_crossentropy',
                        metrics=['accuracy'])

inception_checkpoint = ModelCheckpoint('inception_initial.h5', monitor='val_loss', save_best_only=True, verbose=1)
inception_early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)
lr_scheduler = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1, min_lr=1e-7)

train_generator = train_datagen.flow(X_train, y_train, batch_size=32, shuffle=True)

inception_history = inception_model.fit(
    train_generator,
    epochs=20,
    validation_data=val_generator,
    callbacks=[inception_checkpoint, inception_early_stop, lr_scheduler]
)

"""### **Fine-Tuning InceptionV3**
40 epochs during fine-tuning

"""

inception_model.load_weights('inception_initial.h5')

for layer in inception_base.layers:
    layer.trainable = True


inception_model.compile(optimizer=Adamax(learning_rate=1e-5),
                        loss='categorical_crossentropy',
                        metrics=['accuracy'])


inception_finetune_checkpoint = ModelCheckpoint('inception_finetuned.h5',
                                                 monitor='val_loss',
                                                 save_best_only=True,
                                                 verbose=1)

inception_finetune_earlystop = EarlyStopping(monitor='val_loss',
                                             patience=5,
                                             restore_best_weights=True,
                                             verbose=1)


inception_finetune_history = inception_model.fit(
    train_generator,
    epochs=40,  # 40 epochs during fine-tuning
    validation_data=val_generator,
    callbacks=[inception_finetune_checkpoint, inception_finetune_earlystop, lr_scheduler]
)

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(inception_history.history['accuracy'], label='Train Accuracy (initial)')
plt.plot(inception_history.history['val_accuracy'], label='Val Accuracy (initial)')
plt.plot(inception_finetune_history.history['accuracy'], label='Train Accuracy (fine-tune)')
plt.plot(inception_finetune_history.history['val_accuracy'], label='Val Accuracy (fine-tune)')
plt.title('Training and Validation Accuracy (InceptionV3)')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(inception_history.history['loss'], label='Train Loss (initial)')
plt.plot(inception_history.history['val_loss'], label='Val Loss (initial)')
plt.plot(inception_finetune_history.history['loss'], label='Train Loss (fine-tune)')
plt.plot(inception_finetune_history.history['val_loss'], label='Val Loss (fine-tune)')
plt.title('Training and Validation Loss (InceptionV3)')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

from tensorflow.keras.models import load_model


best_inception_model = load_model('inception_finetuned.h5')


inception_test_loss, inception_test_acc = best_inception_model.evaluate(test_generator, verbose=1)

print(f" InceptionV3 Test Accuracy: {inception_test_acc:.4f}")
print(f" InceptionV3 Test Loss: {inception_test_loss:.4f}")

"""**Download Best Model To Use In Streamlit**"""

from google.colab import files
files.download('inception_finetuned.h5')

"""### **Metrics for best InceptionV3 model**

**Classification Report**
"""

from sklearn.metrics import classification_report
import numpy as np

y_pred_probs = best_inception_model.predict(test_generator)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.argmax(y_test, axis=1)


print(classification_report(y_true, y_pred, target_names=classes))

"""**Confusion Matrix**"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt


cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=classes,
            yticklabels=classes)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - InceptionV3 Fine-Tuned')
plt.show()

"""**ROC Curve**"""

from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize


y_true_binary = label_binarize(y_true, classes=[0, 1, 2, 3])

fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(len(classes)):
    fpr[i], tpr[i], _ = roc_curve(y_true_binary[:, i], y_pred_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

plt.figure(figsize=(8, 6))
colors = ['blue', 'red', 'green', 'purple']
for i, color in zip(range(len(classes)), colors):
    plt.plot(fpr[i], tpr[i], color=color, lw=2,
             label=f'{classes[i].capitalize()} (AUC = {roc_auc[i]:.2f})')

plt.plot([0, 1], [0, 1], 'k--', lw=2)
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Multiclass ROC Curve - InceptionV3 Fine-Tuned')
plt.legend(loc="lower right")
plt.grid()
plt.show()

"""### **Grid search for Inception V3**

*Grid Search was attempted for InceptionV3, yet best validation results did not generate higher test performance than original configuration. Therefore, data augmentation and learning rate scheduler was applied to original InceptionV3 configuration to improve accuracy and minimize loss*
"""